// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class Channel
{
    public int ChannelId { get; set; }

    public string ChannelName { get; set; }

    public string ChannelCode { get; set; }

    public string ChannelDescription { get; set; }

    public byte[] ChannelLogo { get; set; }

    public int? CompanyId { get; set; }

    public int? ActiveStatus { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ChangedOn { get; set; }

    public string CreatedBy { get; set; }

    public string ChangedBy { get; set; }

    public string LicenseCode { get; set; }

    public virtual ICollection<ChannelsConfiguration> ChannelsConfigurations { get; set; } = new List<ChannelsConfiguration>();
}