// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class ChannelGroup
{
    public int ChannelGroupId { get; set; }

    public string ChannelGroupName { get; set; }

    public int? ActiveStatus { get; set; }

    public int? CompanyId { get; set; }

    public int? ChannelId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Company Company { get; set; }
}