// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class ChannelsConfiguration
{
    public int ChannelConfigId { get; set; }

    public int? ChannelId { get; set; }

    public string Scte { get; set; }

    public string Frames { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Channel Channel { get; set; }
}