// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class CommercialSchedule
{
    public int CommercialScheduleId { get; set; }

    public int? ChannelId { get; set; }

    public DateTime? TelecastDate { get; set; }

    public int? ProgramId { get; set; }

    public int? BreakRelativityId { get; set; }

    public int? OrderNumber { get; set; }

    public string CommercialMaterialId { get; set; }

    public string CommercialMaterialName { get; set; }

    public int? CommercialDurationSec { get; set; }

    public string BrandId { get; set; }

    public string BrandName { get; set; }

    public string AdvertisementId { get; set; }

    public string AdvertisementName { get; set; }

    public TimeSpan? AdvertisementStartTime { get; set; }

    public TimeSpan? AdvertisementEndTime { get; set; }

    public string ReconciliationId { get; set; }

    public DateTime? CreatedOn { get; set; }
}