// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class Company
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string CompanyCode { get; set; }

    public string Address { get; set; }

    public string ContactNumber { get; set; }

    public string MailAddress { get; set; }

    public int? ActiveStatus { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ICollection<ChannelGroup> ChannelGroups { get; set; } = new List<ChannelGroup>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}