// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class ErrorLog
{
    public int ErrorId { get; set; }

    public DateTime? ErrorDateTime { get; set; }

    public string ErrorLocateAt { get; set; }

    public string ErrorDescription { get; set; }

    public int? ErrorLineNumber { get; set; }

    public int? ChannelId { get; set; }
}