// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class HotClipHdr
{
    public int HotClipHdrId { get; set; }

    public string HotClipNameTitle { get; set; }

    public string HotClipDescription { get; set; }

    public int? ColumnCount { get; set; }

    public int? RowCout { get; set; }

    public int? ActiveStatus { get; set; }

    public int? UserId { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ChangedOn { get; set; }

    public string ChangedBy { get; set; }

    public int? ChannelId { get; set; }
}