// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class HotClipDtl
{
    public int HotClipDtlId { get; set; }

    public int? HotClipHdrId { get; set; }

    public int? MediaId { get; set; }

    public int? ColumnNumber { get; set; }

    public int? RowNumber { get; set; }
}