// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CLSSContentSchedulerSTT_API.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CLSSContentSchedulerSTT_API.Models
{
    public partial interface IClssContentSchedulerSTTContextProcedures
    {
        Task<List<SPChannelsResult>> SPChannelsAsync(string ActionType, int? ChannelId, string ChannelName, int? ChannelCode, string ChannelDescription, byte[] ChannelLogo, int? CompanyId, int? ActiveStatus, string LicenseCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SPChanneltoUserResult>> SPChanneltoUserAsync(int? ChannelId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SPUserChannelMapResult>> SPUserChannelMapAsync(int? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SPUserChannelPopupResult>> SPUserChannelPopupAsync(int? Userid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SPUsertoChannelResult>> SPUsertoChannelAsync(int? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SPUserTypeMasterResult>> SPUserTypeMasterAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SPUserValidationResult>> SPUserValidationAsync(string UserName, string Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
