// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class Language
{
    public int LanguageId { get; set; }

    public string LanguageName { get; set; }

    public string LanguageDescription { get; set; }

    public int? ActiveStatus { get; set; }
}