// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class MediaMaster
{
    public int MediaId { get; set; }

    public string MediaNameTitle { get; set; }

    public string MediaCaption { get; set; }

    public int? MediaTypeId { get; set; }

    public string AlbumName { get; set; }

    public TimeSpan? MediaDuration { get; set; }

    public int? MediaDurationMilliseconds { get; set; }

    public byte[] MediaImages { get; set; }

    public string MediaLocation { get; set; }

    public TimeSpan? TrimStartTime { get; set; }

    public TimeSpan? TrimEndTime { get; set; }

    public TimeSpan? PreviewStartTime { get; set; }

    public TimeSpan? PreviewEndTime { get; set; }

    public TimeSpan? VoiceStartTime { get; set; }

    public int? MusicLabelId { get; set; }

    public int? ReleaseYear { get; set; }

    public string Tempo { get; set; }

    public string TempoInfo { get; set; }

    public string Mood { get; set; }

    public string GenreInfo { get; set; }

    public string Gain { get; set; }

    public int? LanguageId { get; set; }

    public string MediaGenre { get; set; }

    public string MediaSubGenre { get; set; }

    public string Popularity { get; set; }

    public string SoundFeel { get; set; }

    public string Lyrics { get; set; }

    public string LyricsInfo { get; set; }

    public string LyricsLanguage { get; set; }

    public string Remarks { get; set; }

    public int? ActiveStatus { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string EndDateStatus { get; set; }

    public string VideoStatus { get; set; }

    public string Keyer { get; set; }

    public string Templates { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ChangedOn { get; set; }

    public string ChangedBy { get; set; }

    public int? ChannelId { get; set; }

    public virtual ICollection<MediaTcinout> MediaTcinouts { get; set; } = new List<MediaTcinout>();

    public virtual MediaType MediaType { get; set; }
}