// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class MediaTypeDetail
{
    public int MediaTypeDetailId { get; set; }

    public string MediaTypeDetailName { get; set; }

    public string MediaTypeDetailDescription { get; set; }

    public string MediaTypeDetailColor { get; set; }

    public int? MediaTypeHeaderId { get; set; }

    public TimeSpan? AverageDuration { get; set; }

    public int? MediaCount { get; set; }

    public int? ActiveStatus { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }
}