// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class MediaType
{
    public int MediaTypeId { get; set; }

    public string MediaTypeCode { get; set; }

    public string MediaTypeDescription { get; set; }

    public string MediaTypeColor { get; set; }

    public int? ActiveStatus { get; set; }

    public int? CompanyId { get; set; }

    public int? ChannelId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ICollection<MediaMaster> MediaMasters { get; set; } = new List<MediaMaster>();
}