// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class MediaTcinout
{
    public int UniqueId { get; set; }

    public int? MediaId { get; set; }

    public TimeSpan? Tcin { get; set; }

    public TimeSpan? Tcout { get; set; }

    public int? ChannelId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual MediaMaster Media { get; set; }
}