// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class MusicLabel
{
    public int MusicLabelId { get; set; }

    public string MusicLabel1 { get; set; }

    public string MusicLabelDescription { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? ActiveStatus { get; set; }

    public int? CompanyId { get; set; }

    public int? ChannelId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ChangedOn { get; set; }

    public string ChangedBy { get; set; }
}