// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class PlayoutHdr
{
    public int PlayoutHdrId { get; set; }

    public DateTime? PlayoutDate { get; set; }

    public int? CompanyId { get; set; }

    public int? ChannelId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ChangedOn { get; set; }

    public string ChangedBy { get; set; }

    public virtual ICollection<PlayoutDtl> PlayoutDtls { get; set; } = new List<PlayoutDtl>();
}