// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class PlayoutDtl
{
    public int OnairId { get; set; }

    public int? PlayoutHdrId { get; set; }

    public int? MediaId { get; set; }

    public string MediaName { get; set; }

    public TimeSpan? MediaStartTime { get; set; }

    public TimeSpan? MediaEndTime { get; set; }

    public TimeSpan? MediaDuration { get; set; }

    public int? MediaDurationMilliseconds { get; set; }

    public string MediaType { get; set; }

    public TimeSpan? OnairStartTime { get; set; }

    public TimeSpan? OnairEndTime { get; set; }

    public int? ProgramId { get; set; }

    public string ProgramName { get; set; }

    public TimeSpan? ProgramStartTime { get; set; }

    public TimeSpan? ProgramEndTime { get; set; }

    public string OnairStatus { get; set; }

    public int? OnairOrderNumber { get; set; }

    public int? NodeKey { get; set; }

    public string Marker { get; set; }

    public string Remarks { get; set; }

    public TimeSpan? Som { get; set; }

    public TimeSpan? Eom { get; set; }

    public virtual PlayoutHdr PlayoutHdr { get; set; }
}