// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class ProgramTemplateHeader
{
    public int ProgramTemplateHeaderId { get; set; }

    public string ProgramTemplateHeaderName { get; set; }

    public string ProgramTemplateHeaderDescriptino { get; set; }

    public TimeSpan? ProgramTemplateHeaderDuration { get; set; }

    public int? SingleTrack { get; set; }

    public int? ProgramId { get; set; }

    public int? ActiveStatus { get; set; }

    public int? ChannelId { get; set; }

    public int? CompanyId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }
}