// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class Resource
{
    public int UniqueId { get; set; }

    public int ResourceId { get; set; }

    public string ResourceName { get; set; }

    public int? Color { get; set; }

    public byte[] Image { get; set; }

    public string CustomField1 { get; set; }
}