// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CLSSContentSchedulerSTT_API.Models
{
    public partial class SPChannelsResult
    {
        public int ChannelId { get; set; }
        public string ChannelName { get; set; }
        public string ChannelCode { get; set; }
        public string ChannelDescription { get; set; }
        public byte[] ChannelLogo { get; set; }
        public int? CompanyId { get; set; }
        public int? ActiveStatus { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ChangedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ChangedBy { get; set; }
        public string LicenseCode { get; set; }
    }
}
