// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CLSSContentSchedulerSTT_API.Models
{
    public partial class SPUserChannelPopupResult
    {
        public int UserId { get; set; }
        public int ChannelId { get; set; }
        public string ChannelName { get; set; }
        public byte[] channellogo { get; set; }
    }
}
