// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CLSSContentSchedulerSTT_API.Models
{
    public partial class SPUserTypeMasterResult
    {
        public int UserTypeId { get; set; }
        public string UserType { get; set; }
    }
}
