// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public byte[] UserImage { get; set; }

    public int? UserTypeId { get; set; }

    public int? CompanyId { get; set; }

    public int? ActiveStatus { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<UserNote> UserNotes { get; set; } = new List<UserNote>();

    public virtual UserType UserType { get; set; }
}