// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLSSContentSchedulerSTT_API.Models;

public partial class UserNote
{
    public int UserNotesId { get; set; }

    public int? UserId { get; set; }

    public string Notes { get; set; }

    public int? ActiveStatus { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public int? ChannelId { get; set; }

    public virtual User User { get; set; }
}